---
title: "Syllabus"
params:
  course_number: "301"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r}
#| echo: false
#| message: false
course_number <- params$course_number
extra_text <- if(course_number == "302") "In addition to the post-field experience reflect, students taking the laboratory component will have to complete an additional assignment composed of writing an outbreak investigation plan to an instructor provided prompt." else ""
```

# Course title and instructors

**Title:** BIO`{r} course_number`: International Field Epidemiology and Tropical Medicine  
**Semester:** Summer 2025  

**Course Director:** John W. Sanders, MD, MPHT&M  
**Email:** jwsander@wakehealth.edu  

**Course Co-Director:** Michael E. DeWitt, MS  
**Email:** medewitt@wakehealth.edu or dewime23@wfu.edu  

Additional instructors:

- Brinkley R. Bellotti, VMD, PhD, research assistant professor Wake Forest University School of Medicine <br>
- Andres G. "Willy" Lescano, PhD, director of the Emerging Infections and Climate Change Unit (EMERGE) and associate professor at the Universidad Peruana Cayetano Heredia (UPCH) <br>
- Marlon Saavedra certified biologist at the Universidad Peruana Cayetano Heredia (UPCH) <br>

Additionally, we be will joined by specialists in the field of infectious diseases, zoonoses, and vector-borne diseases from the Universidad Peruana Cayetano Heredia (UPCH) and the Gorgas Memorial Institute for Health Studies (IGME) in Panama.

# Course description
The course takes a hands-on approach to the study of  Infectious Disease Ecology, highlighting its connection to One Health principles and the responses of socioecological systems to global change.
It does so by providing students with an engaged field epidemiology experience in a tropical setting using the scenario (simulated) of an outbreak of a newly emerged zoonotic infectious disease.
Students are first-hand practitioners in the front-line of a “Hot Zone” and work shoulder-to-shoulder with public health practitioners and medical fellows (post-resident MD infectious disease specialists) and engage multiple local stakeholders.
By the end of the course students will have a deep understanding of responding to an outbreak including comfort in setting up a field lab and performing a field investigation similar to those conducted by the US Centers for Disease Control and Prevention and the World Health Organization.
This intensive summer course offers a thorough overview of epidemiological principles and practices as applied to public health field studies, combining lectures, case studies, and hands-on training in designing, conducting, and publishing epidemiological field investigations.

# Learning outcomes 

- Understand the importance of the One Health approach to public health including the role of ecology in our understanding of infectious diseases
- Understand the principles of field epidemiology and its importance in public health response
- Understand the principles of infectious disease ecology and zoonoses and their relevance to outbreaks of pathogens of animal and human importance
- Understand how to design, conduct, and publish field epidemiology investigations
- Learn the techniques used to identify reservoirs including small mammals and vectors

# Textbook and other resources

The primary textbook for this course is available online at [Introduction to Field Epidemiology and Outbreak Response](https://fieldepi.wakeforestid.com) and was created by the instructors for this course.
Any additional resources that are required will be provided in the course.
Some articles that we will review will include:

- Plowright RK, Parrish CR, McCallum H, Hudson PJ, Ko AI, Graham AL, et al. Pathways to zoonotic spillover. Nat Rev Microbiol 2017;15:502–10. https://doi.org/10.1038/nrmicro.2017.45.
- Taylor LH, Taylor LH, Latham SM, Woolhouse MEJ. Risk factors for human disease emergence. Philosophical Transactions of the Royal Society B 2001;356:983–9. https://doi.org/10.1098/rstb.2001.0888.
- Goodman RA, Buehler JW, Koplan JP. THE EPIDEMIOLOGIC FIELD INVESTIGATION: SCIENCE AND JUDGMENT IN PUBLIC HEALTH PRACTICE. American Journal of Epidemiology 1990;132:9–16. https://doi.org/10.1093/oxfordjournals.aje.a115647.
- Lloyd-Smith JO, George DB, Pepin KM, Pitzer VE, Pulliam JRC, Dobson AP, et al. Epidemic dynamics at the human-animal interface. Science 2009;326:1362–7. https://doi.org/10.1126/science.1177345. 


Some additional resources that are useful for a deeper understanding of this course include:

- The CDC Field Epidemiology Manual by Rasmussen and Goodman
- The Outbreak Atlas by Katz and Moore

# Course structure and schedule

This course is composed into two parts:

1. Zoom-based lectures and discussion regarding field epidemiology, infectious disease ecology, the life cycle and clinical presentation of pathogens of human importance (parasites, viruses, and bacteria), global health outbreak response, and basic principles of animal disection.

2. Field-based activities in Lima and Tumbes, Peru where students will be able to apply the principles they have learned through hands-on activities and additional didactic sessions from local experts.

## Part 1: Zoom-based lectures and discussion

| Topic | Date :| Instructor :|
|------------------------|------|------------|
| 1. Global surveillance and outbreak response | May 28 | Sanders |
| 2. Overview of tropical diseases, clinical relevance, and global health priorities | May 28 | Sanders |
| 3. The Incident Command System | May 28 | DeWitt |
| 4. Infectious disease ecology and zoonoses | May 28 | DeWitt |
| 5. Diagnostic approaches for infectious diseases | May 29 | Sanders
| 6. Basics of parasitology | May 29 | Sanders
| 7. Basics of vector-borne diseases | May 29 | Sanders
| 8. Introduction to animal dissection | May 29 | Bellotti
| 9. Introduction to dissection techniques | May 29 | Bellotti
| 10. Travel medicine and field safety during epidemiologic investigations | May 30 | Sanders
| 11. Epidemiology 101: The basics of epidemiology | May 30 | Bellotti & DeWitt
| 12. Data management and geospatial analysis for field epidemiology | May 30 | DeWitt
| 13. An overview of Northern Peru | May 30 | TBD



## Part 2: Field-based activities

The second part of the course will be held in Lima and Tumbes, Peru.
The classroom dates are June 2-11, 2025.
Note that these topics are subject to change depending on the progress of the course and the weather.
June 8th does not have any academic activities planned and can be used by the students to rest and prepare final reports.

| Topic | Date | Instructor |
|----------------------------------|------|------|
| 1. CDC's 10 Steps for an Outbreak Investigation. | June 2 | Lescano & Sanders |
| 2. Design of field studies: components of the outbreak investigation. | June 2 | Lescano & Sanders |
| 3. Session 1: Outbreak Initial report and request for support. | June 2 | Lescano & Sanders |
| 4. Recognize the infrastructure available at the core facility (UPCH-Centro de Salud Global)  | June 3 | Lescano & Sanders |
| 5. Visit Centro De Salud Zarumilla and GERESA for local coordination with health authorities, get a better understanding of local disease epidemiology. | June 2 | Lescano |
| 6. Examination and delimitation of the working area in Campo amor | June 3 | All |
| 7. Review of case definition and questionaire forms used during field investigations. Discuss how protocols and field epidemiology is conducted. | June 3 | Lescano & Sanders |
| 8. Review of basic analytical techniques for epidemiology | June 3 | DeWitt |
| 9. Review case investigation forms | June 3 | DeWitt |
| 10. Population census and identification of individuals who meet the inclusion criteria for the case study in Campo amor, household surveys and biological samples collection from humans (Campo amor) | June 4 | All |
| 11. One health perspective on ectoparasite-borne emerging zoonotic diseases and studies of reservoirs. | June 4 | Lescano, Sanders, DeWitt |
| 12. Material preparation for small mammals traps | June 4 | Lescano |
| 13. Setting traps for small mammals. | June 4 | Lescano |
| 14. Capture, necropsy, and tissue sampling of small mammals.| June 5 | Lescano |
| 15. Outbreak investigation: develop report and analyze data. | June 5 | Lescano, Sanders, DeWitt |
| 16. Sampling of livestock, domestic animals and environment. | June 5 | Lescano |
| 17. Collection of pupae and larvae of Aedes and Cuclidaeos and capture of Aedes and cuclideos adults with Prokopack aspirator.  Inspection of flower vases in cementery Caleta la cruz. 
Aedes traps: BG, ovitrap, prokopack. | June 6 | Gorgas |
| 18. Collection of pupae and larvae Anopheles around the CSG | June 6 | Gorgas |
| 19. Capture of adult Anopheles with light traps (CDC), live bait and Shannon traps| June 6 | Gorgas |
| 20. Collecting Aedes and Anopheles traps | June 7 | Gorgas |
| 21. Morphology, development and dissection of mosquitoes. | June 7 | Gorgas |
| 22. Insecticides resistance testing | June 7 |  Saavedra|
| 23. Necropsy of an infected pig with Cysticercosis. | June 9 | Muro |
| 24. Basic parasitology and stool microscopy. | June 9 | Mayra Elizalde |
| 25. Bats: setting traps and catch-release activity | June 9 | Lescano |
| 26. Identification of ectoparasite species | June 10 | Lescano |
| 27. Introduction to the management of geographic data | June 10 | Gorgas |
| 28. Shadow hospital rounds at Instituto de Medicina Tropical Alexander von Humboldt | June 11 | Lescano |


# Grades and assignments

Students' evaluation will be based on their attendance and participation on course activities, as well as their performance during all the course activities in Lima and Tumbes.
Students will have to complete a pre-trip reading and reflection assignment as well as a post-field experience reflection upon their return to the United States.
The pre-trip reading and reflection assignment will assigned on the first day of class and will be due on the second day of class.
`{r} extra_text`

|Activity | Weight|
|----------|------|
|Attendance | 10% |
|Performance during field activities | 50% |
|Post-field experience reflection | 20% |
|Pre-trip reading and reflection assignment | 20% |


# Course policies

**Attendance:** Attendance is mandatory for all components of this course.
Please alert the instructors if you are unable to attend for any reason

**Late/Makeup work:** Due dates for the assignments are provided on the course syllavbus and the course schedule. Unless otherwise stated, assignments are due on those days. 
We recognize that there are sometimes extenuating circumstances (i.e., live happens) and as such we will allow you to submit assignments up to 2 days late without any penalty.
If there is a valid reason for requiring an extension, please contact the instructors as soon as possible and **before the due date**.
We can evaluate late work on a case-by-case basis.

**Artificial intelligence:** Artificial intelligence tools and large language models such as ChatGPT, Claude, and Gemini are now part of the academic and professional landscape and we encourage you to find ways to use them to enhance your learning. 
However, if you use these tools, you must cite your sources and provide a detailed description of the tools you used to complete the assignment.
In no way can these tools take the place of your own work and understanding of the material. They should be used to supplement your learning, not replace it.
You are ultimately responsible for your work including content and the use of valid citations and references.
Using these tools without proper attribution is plagiarism and will be treated as such.


# Department/School/University policies

**Academic Integrity:** Wake Forest University is committed to a culture of academic integrity. As a part of this community, you share the responsibility for creating a place of honesty, intellectual curiosity, and individual accountability. As you committed to with your honor pledge signature, you agree “not to deceive any member of the community; not to steal, cheat, or plagiarize on academic work; and not to engage in any other form of academic misconduct.” If you have questions about documenting your work, working with external sources, working with peers on assigned work, etc., consult with me as soon as possible. Instances of academic dishonesty will be referred to the Honor and Ethics Council.

**Accessibility:** Wake Forest University provides reasonable accommodations to students with disabilities. If you are in need of an accommodation, then please contact me privately as early in the term as possible. Retroactive accommodations will not be provided. Students requiring accommodations must also consult the Center for Learning, Access, and Student Success (118 Reynolda Hall, 336-758-5929, class.wfu.edu).

**Accommodations for Religious or Spiritual Practices:** Wake Forest University benefits from the multitude of faiths and spiritual identities held by members of our learning community. Our institution values this religious and spiritual diversity and supports providing academic accommodations to students for religious or spiritual observations. The Office of Diversity and Inclusion has developed a calendar of common Holy Days observed by many individuals on our campus. Should you need such accommodations this semester, you should email me as soon as possible to ensure we have time to develop equitable alternatives. You are encouraged to use this [template](https://chaplain.wfu.edu/news-events/holy-days/holy-day-accommodation/), developed by the Office of the Chaplain, to make these requests.

**Class recordings** In case any class recordings are provided they are reserved only for students in this class for educational purposes and are protected under FERPA. The recordings should not be shared outside the class in any form. Violation of this restriction by a student could lead to Student Misconduct proceedings.

# Syllabus change notice

This syllabus and the dates herein are subject to change.


